services: 
  webapp:
    build: .
    command:  bash -c "python -m app.initialize_db && gunicorn --workers 4 -b 0.0.0.0:5000 --preload --pythonpath flask-app --log-level=debug app.wsgi:app"
    volumes: 
      - .:/flask-app
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      PYTHONPATH: /flask-app
      FLASK_APP: "app:create_app"
      TRANSACTION_SECRET_KEY: "my_secret_key"
      DATABASE_URL: "postgresql://flaskuser:flaskpassword@db:5432/flaskdb"
      USER_SECRET_KEY: "my_secret_key"
      MAX_TICKETS_PER_ORDER: 8
      SESSION_LOGOUT_TIMEOUT_MINUTES: 5


  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "psql --username flaskuser --dbname flaskdb -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: