version: '3.8'
services: 
  webapp:
    build: .
    command: python startup.py
    volumes: 
      - ./:app
    ports: 
      - '5000:5000'
    depends_on:
      - db


  db: 
    image: postgres:16.3-bookworm
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword

volumes:
  postgres_data: